-- local M = {
--     "lukas-reineke/indent-blankline.nvim",
-- 	main = "ibl",
--     opts = {
--         indent = { char = "▏" },
--         space_char_blankline = " ",
--         show_trailing_blankline_indent = true,
--         show_current_context = false,
--         show_current_context_start = false,
--         space_char_highlight_list = {
--             "IndentBlanklineIndent3"
--         },
--     },
-- }
-- 
-- return M
return {}
